      - name: install mysql database server
        apt:
          name: "{{ item }}"
          state: present 
        with_items:
          - mysql-server
          - mysql-client

      - name: start mysql server
        service:
          name: mysql
          state: started
          enabled: yes

      - name: create a database
        mysql_db:
          name: "{{ db_name }}"
          state: present
          login_unix_socket: /var/run/mysqld/mysqld.sock

      - name: create a user
        mysql_user:
          name: "{{  db_user }}"
          password: "{{ db_password }}"
          priv: '*.*:ALL'
          state: present
          login_unix_socket: /var/run/mysqld/mysqld.sock

  