  - name: install dependencies
    apt: 
      name: "{{ item }}"
      state: present
    become: yes  
    with_items:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - build-essential
      - python3-mysqldb

  - include_tasks: db.yml
  - include_tasks: web.yml